version: '3.8'

services:
  db_utama:
    image: mysql:8.0
    container_name: mysql_proyek_abl
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_layanan_mahasiswa
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_fresh:/var/lib/mysql

  # 🐳 phpMyAdmin Resmi Docker (Port 8080)
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin_proyek_abl
    restart: always
    ports:
      - "8080:80"
    environment:
      PMA_HOST: db_utama
      PMA_USER: root
      PMA_PASSWORD: rootpassword

volumes:
  mysql_data_fresh: