version: '3.8'

services:
  db_utama:
    image: mysql:8.0
    container_name: mysql_proyek_abl
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: db_layanan_mahasiswa
    ports:
      - "3306:3306"
    volumes:
      - mysql_data_volume:/var/lib/mysql

volumes:
  mysql_data_volume: